import type {
  Payment,
  PaymentWithDetails,
  PaymentWithParticipants,
  Profile,
} from '@/core/domain/entities/payment';
import type { IPaymentRepository } from '@/core/domain/repositories';
import { createClient } from '@/lib/supabase/server';

export class SupabasePaymentRepository implements IPaymentRepository {
  async create(
    payment: Omit<Payment, 'id' | 'createdAt'>,
    participantIds: string[],
  ): Promise<void> {
    const supabase = await createClient();

    // Insert payment - ID is generated by DB (gen_random_uuid())
    const { data: paymentData, error: paymentError } = await supabase
      .from('payments')
      .insert({
        group_id: payment.groupId,
        payer_id: payment.payerId,
        amount: payment.amount,
        description: payment.description,
      })
      .select()
      .single();

    if (paymentError) throw new Error(paymentError.message);

    // Insert participants
    const participantRecords = participantIds.map((profileId) => ({
      payment_id: paymentData.id,
      profile_id: profileId,
    }));

    const { error: participantsError } = await supabase
      .from('payment_participants')
      .insert(participantRecords);

    if (participantsError) {
      // Rollback
      await supabase.from('payments').delete().eq('id', paymentData.id);
      throw new Error(participantsError.message);
    }
  }

  async update(
    paymentId: string,
    payment: Partial<Omit<Payment, 'id' | 'groupId' | 'createdAt'>>,
    participantIds: string[],
  ): Promise<void> {
    const supabase = await createClient();

    // 1. Update payment record
    const { error: paymentError } = await supabase
      .from('payments')
      .update({
        payer_id: payment.payerId,
        amount: payment.amount,
        description: payment.description,
      })
      .eq('id', paymentId);

    if (paymentError) throw new Error(paymentError.message);

    // 2. Update participants (delete and insert)
    // First, delete existing participants
    const { error: deleteError } = await supabase
      .from('payment_participants')
      .delete()
      .eq('payment_id', paymentId);

    if (deleteError) throw new Error(deleteError.message);

    // Then, upsert new participants to avoid duplicate key errors
    const participantRecords = participantIds.map((profileId) => ({
      payment_id: paymentId,
      profile_id: profileId,
    }));

    const { error: upsertError } = await supabase
      .from('payment_participants')
      .upsert(participantRecords);

    if (upsertError) throw new Error(upsertError.message);
  }

  async getByIdWithParticipants(
    paymentId: string,
  ): Promise<PaymentWithParticipants | null> {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('payments')
      .select(
        `
        id,
        payer_id,
        amount,
        participants:payment_participants(profile_id)
      `,
      )
      .eq('id', paymentId)
      .single();

    if (error) return null;

    return {
      id: data.id,
      payerId: data.payer_id,
      amount: data.amount,
      participantIds:
        (data.participants as unknown as { profile_id: string }[])?.map(
          (pr) => pr.profile_id,
        ) || [],
    };
  }

  async getByGroupId(groupId: string): Promise<PaymentWithDetails[]> {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('payments')
      .select(
        `
        *,
        payer:profiles!payer_id(id, name),
        participants:payment_participants(
          profile:profiles(id, name)
        )
      `,
      )
      .eq('group_id', groupId)
      .order('created_at', { ascending: false });

    if (error) throw new Error(error.message);

    return (data || []).map((p) => ({
      id: p.id,
      groupId: p.group_id,
      payerId: p.payer_id,
      amount: p.amount,
      description: p.description,
      createdAt: p.created_at,
      payerName: (p.payer as unknown as Profile)?.name || 'Unknown',
      participantNames:
        (
          p.participants as unknown as {
            profile: Profile | null;
          }[]
        )?.map((pr) => pr.profile?.name || 'Unknown') || [],
    }));
  }

  async getWithParticipantsByGroupId(
    groupId: string,
  ): Promise<PaymentWithParticipants[]> {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('payments')
      .select(
        `
        id,
        payer_id,
        amount,
        participants:payment_participants(profile_id)
      `,
      )
      .eq('group_id', groupId);

    if (error) throw new Error(error.message);

    return (data || []).map((p) => ({
      id: p.id,
      payerId: p.payer_id,
      amount: p.amount,
      participantIds:
        (p.participants as unknown as { profile_id: string }[])?.map(
          (pr) => pr.profile_id,
        ) || [],
    }));
  }

  async delete(paymentId: string, groupId: string): Promise<void> {
    const supabase = await createClient();
    const { error } = await supabase
      .from('payments')
      .delete()
      .eq('id', paymentId)
      .eq('group_id', groupId);

    if (error) throw new Error(error.message);
  }
}
