/**
 * Type definitions for payment-related operations in Equalin.
 * These types are used across the application for type safety and consistency.
 */

/**
 * Represents a user profile in the system.
 */
export interface Profile {
  id: string;
  name: string;
}

/**
 * Represents a payment record in the database.
 * Amounts are stored as integers representing the smallest currency unit (cents).
 */
export interface Payment {
  id: string;
  group_id: string;
  payer_id: string;
  amount: number; // stored as integer (cents)
  description: string | null;
  created_at: string;
}

/**
 * Represents a record in the payment_participants junction table.
 * Links payments to the profiles that participate in sharing the expense.
 */
export interface PaymentParticipant {
  payment_id: string;
  profile_id: string;
}

/**
 * Extended payment type that includes payer name and participant names.
 * Used for displaying payment information in the UI.
 */
export interface PaymentWithDetails extends Payment {
  payer_name: string;
  participant_names: string[];
}

/**
 * Represents a member's financial balance in a group.
 * Used for settlement calculations.
 */
export interface MemberBalance {
  profile_id: string;
  name: string;
  paid: number; // total amount paid (in cents)
  owed: number; // total share of expenses (in cents)
  balance: number; // paid - owed (in cents)
}

/**
 * Represents a settlement transaction showing who should pay whom.
 * Generated by the settlement calculation algorithm.
 */
export interface SettlementTransaction {
  from: string; // profile name of the person paying
  to: string; // profile name of the person receiving
  amount: number; // amount in cents
}
